### ISSUE TITLE
Allow to set custom plugin name in 'generic' plugins.

### ISSUE THREAD

**Issue by rpv-tomsk** [collectd/collectd#1944]
Allow to set custom plugin name in 'generic' plugins.

There are some 'generic' plugins exists in Collectd. 
The proposal is to add 'Plugin' option to their configuration, so reported plugin name can be changed.

Related PR list:
- [X] Curl_xml: Custom names for plugin/plugin instances #1558
- [X] Curl_JSON: Custom plugin name; PHP-FPM configuration example #1563
- [X] Allow custom plugin name for 'curl', 'memcachec', 'tail' and 'tail_csv' plugins. #1681
- [X] Allowed custom plugin name in 'dbi', 'oracle' and 'postgresql' plugins. #1707
- [X] Filecount plugin: Custom values for reported plugin, type and type instance #1979
- [X] Table plugin: Allow custom plugin name to be reported #2435

**Comment by octo** [comment]
As mentioned in #1681:

> You're right in that there is no "service" label in *collectd* and *plugin* can kind of fill that position.

In other words, I'm okay with this chance so long as it is consistently implemented, i.e. all plugins have the same config option which behaves the same way.

**Comment by rpv-tomsk** [comment]
Collectd Java plugin has own config option, `PluginName`:

```
=item B<PluginName> I<name>

When set, overrides the default setting for the I<plugin> field
(C<GenericJMX>).
```

**Comment by rpv-tomsk** [comment]
Added improvements to `filecount` plugin.

**Comment by rpv-tomsk** [comment]
If `processes` plugin will be improved to support per-process/per-group configuration (https://github.com/collectd/collectd/pull/836#issuecomment-252503632), then it also can be improved to support custom plugin names reported.

**Comment by rpv-tomsk** [comment]
Hi! 

Let's merge these changes?

**Comment by rpv-tomsk** [comment]
Ping.

**Comment by rpv-tomsk** [comment]
Hi!

Let's merge these changes?

**Comment by octo** [comment]
All done \o/
