### ISSUE TITLE
Feature request: Notify about service/host restart based on 'uptime' metric

### ISSUE THREAD

**Issue by rpv-tomsk** [collectd/collectd#2852]
Proposal was to create new plugin to notify about service/host restart based on 'uptime' metric.

If new metric value is less than previous - notify about host/service restart.
If metric value is _equal_ .... notify about strange situation.
If metric value is missing - host/service is down.

At first glance, this will be a new plugin and if can be based on `threshold` plugin code.

For services, which does not provide uptime as value, we can implement own `connection_uptime` metric which will report uptime of Collectd-to-service connecton.

- [x] implement new plugin (#3159)
- [x] add `uptime` to `memcached` plugin (#3160)
- [ ] add `uptime` to `routeros` plugin
- [x] add `uptime` to `mysql` plugin (#3125)

Also possible: `teamspeak2` plugin.

Plugins which already has `uptime` metric:
 - `uptime` plugin
 - `powerdns` plugin
 - `redis` plugin
 - `varnish` plugin

- [x] The plugin itself: #3159

**Comment by sunkuranganath** [comment]
Does the 5.11 milestone still valid here? Seems like more work to be done.

**Comment by dago** [comment]
I agree. Until there is volunteer to work on this one I'll remove the 5.11 milestone.

**Comment by rpv-tomsk** [comment]
>I agree. Until there is volunteer to work on this one I'll remove the 5.11 milestone.

You don't know that you already released this in 5.10 ? 

Very funny.
