### ISSUE TITLE
[collectd 6] aggregation tracking bug

### ISSUE THREAD

**Issue by octo** [collectd/collectd#3588]
This is a tracking issue for migrating the *aggregation plugin* to *collectd 6*.
Progress is tracked in the [collectd&nbsp;6 project](https://github.com/orgs/collectd/projects/1).

The *aggregation plugin* currently doesn't compile and has been disabled in the
automatic builds. Please remove the `--disable-aggregation` line from the
following files:

*   `.cirrus.yml`
*   `.travis.yml`
*   `solaris-ci.flags`

### Next steps

This is an automatically generated todo list. If one of the following steps doesn't make sense, blame the automation. :see_no_evil:

*   [ ] Assign this issue to yourself.
*   [ ] Determine whether the *aggregation plugin* **should** be migrated in the first place. If this is not an obvious "yes", discuss on the [mailing list](https://collectd.org/wiki/index.php/Mailing_list) or at the next [community call](https://collectd.org/wiki/index.php/Community_calls).
*   [ ] Re-enable the *aggregation plugin* in `.cirrus.yml`, `.travis.yml`, and `solaris-ci.flags`.
*   [ ] Change the *aggregation plugin's* write callback to accept a `metric_family_t*` instead of a `value_list_t*`.
*   [ ] Create a pull request referencing this issue.
