### ISSUE TITLE
[collectd 6] apache tracking bug

### ISSUE THREAD

**Issue by octo** [collectd/collectd#3592]
This is a tracking issue for migrating the *apache plugin* to *collectd 6*. Progress is tracked in the [collectd&nbsp;6 project](https://github.com/orgs/collectd/projects/1). Technical guidance for migrating plugins to *collectd 6* is provided in the [V5 to V6 migration guide](https://collectd.org/wiki/index.php/V5_to_v6_migration_guide) topic in the wiki.

The *apache plugin* currently compiles, likely thanks to the backwards compatibility layer.

While the backwards compatibility layer allows the plugin to compile, it likely results in suboptimal metric names. If possible, try to find a *Prometheus exporter* reporting the same metric(s) and use the same naming schema.

### Next steps

This is an automatically generated todo list. If one of the following steps doesn't make sense, blame the automation. :see_no_evil:

*   [ ] Assign this issue to yourself.
*   [ ] Determine whether the *apache plugin* **should** be migrated in the first place. If this is not an obvious "yes", discuss on the [mailing list](https://collectd.org/wiki/index.php/Mailing_list) or at the next [community call](https://collectd.org/wiki/index.php/Community_calls).
*   [ ] If possible, try to find a *Prometheus exporter* reporting the same metric(s) and use the same naming schema.
*   [ ] Update the *apache plugin* to produce a `metric_family_t` and call `plugin_dispatch_metric_famliy()`. You can use the *write_log plugin* to verify that the produced metrics look as expected.
*   [ ] Create a pull request referencing this issue.

**Comment by mrunge** [comment]
The recommended(?) exporter https://github.com/Lusitaniae/apache_exporter has

```
Apache metrics:

# HELP apache_accesses_total Current total apache accesses (*)
# TYPE apache_accesses_total counter
# HELP apache_scoreboard Apache scoreboard statuses
# TYPE apache_scoreboard gauge
# HELP apache_sent_kilobytes_total Current total kbytes sent (*)
# TYPE apache_sent_kilobytes_total counter
# HELP apache_cpu_load CPU Load (*)
# TYPE apache_cpu_load gauge
# HELP apache_up Could the apache server be reached
# TYPE apache_up gauge
# HELP apache_uptime_seconds_total Current uptime in seconds (*)
# TYPE apache_uptime_seconds_total counter
# HELP apache_workers Apache worker statuses
# TYPE apache_workers gauge
# HELP apache_version Apache server version
# TYPE apache_version gauge
# HELP apache_duration_total Total duration of all registered requests
# TYPE apache_duration_total gauge
```
Metrics marked '(*)' are only available if ExtendedStatus is On in apache webserver configuration. In version 2.3.6, loading mod_status will toggle ExtendedStatus On by default.

**Comment by elfiesmelfie** [comment]
https://github.com/collectd/collectd/pull/3826 migrates apache to collectd 6
